server:
  port: 8014
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: mcp-server
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
      connect-timeout: 3
      timeout: 3
  ai:
    mcp:
      server:
        type: async
        name: mcp-server
        version: 1.0.0