server:
  port: 8009
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: text2images
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
