server:
  port: 8002
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: ollama
  ai:
    ollama:
      base-url: "http://192.168.187.166:11434"
      chat:
        model: "qwen3:8b"