server:
  port: 8016
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: mcp-client
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: "qwen-plus-2025-09-11"
    mcp:
      client:
        request-timeout: 60s
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/mcp.json
        enabled: true
        root-change-notification: true