server:
  port: 8010
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: text2voice
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
