server:
  port: 8012
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
spring:
  application:
    name: rag
  # pgvector (不是普通的postgres)
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    # redis stack (不是普通的redis)
    redis:
      host: localhost
      port: 6380
      database: 0
      connect-timeout: 3
      timeout: 3
  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-09-11
      embedding:
        options:
          model: text-embedding-v4
    ollama:
      base-url: http://127.0.0.1:11434
      embedding:
        options:
          model: bge-m3:latest
    vectorstore:
      redis:
        index-name: custom-index
        prefix: custom-prefix
        initialize-schema: true
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 10000